# Generated by GitHub Copilot
# This script copies a file from "server/left4dead2" folder to "custom_files" folder based on a relative path provided as an argument.
# Usage: .\custom_file.ps1 <relative_path>
#  or you can run the script with its batch file wrapper: custom_file(.bat) <relative_path>
# Ensure the script is run with PowerShell

# Get the relative path from the first argument
$RelativePath = $args[0]

if (-not $RelativePath) {
    Write-Output "Please provide the relative path (e.g., cfg/server.cfg) as the first argument."
    exit 1
}

# Define source and target base folders (relative to current directory)
$SourceBase = "server\left4dead2"
$TargetBase = "custom_files"

# Build full source and target paths
$SourceFile = Join-Path $SourceBase $RelativePath
$TargetFile = Join-Path $TargetBase $RelativePath

try {
    # Resolve the full path of the source file, error if not found
    $SourceFileFull = Resolve-Path $SourceFile -ErrorAction Stop

    # Ensure the target directory exists
    $TargetDir = Split-Path $TargetFile -Parent
    if (-not (Test-Path $TargetDir)) {
        New-Item -Path $TargetDir -ItemType Directory -Force | Out-Null
    }

    # Copy the file
    Copy-Item -Path $SourceFileFull -Destination $TargetFile -Force

    Write-Output "Copied '$SourceFileFull' to '$TargetFile'"
}
catch {
    Write-Error "Failed to copy file: $_"
    exit 1
}